### ISSUE TITLE
Complex VC fails to Verify

### ISSUE THREAD

**Issue by BenjaminMoe** [vongohren/verify-issues#1]
I'll use this as a scratch-pad for debugging.

This VC is passing verification

```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "type": [
    "VerifiableCredential"
  ],
  "issuer": "did:key:z6Mkiy4qDuyvcVDHG7zcfEDjmmLchAuk8hy4uAJrQht3wio3",
  "issuanceDate": "2022-04-18T13:30:30Z",
  "credentialSubject": {
    "type": "ContactPoint",
    "id": "did:key:z6MkfwmZep5ZvkHfeXszxhxEuvkmGFRc8H9Nv9ZaQG4vhFzZ",
    "phoneNumber": "+46456812311",
    "identifier": "7870dab0-f8f5-11eb-b356-657b2e987fed"
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2022-04-27T19:20:11Z",
    "verificationMethod": "did:key:z6Mkiy4qDuyvcVDHG7zcfEDjmmLchAuk8hy4uAJrQht3wio3#z6Mkiy4qDuyvcVDHG7zcfEDjmmLchAuk8hy4uAJrQht3wio3",
    "proofPurpose": "assertionMethod",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..Iayl1sv9hNXMvwC8AoDBHYumLpq8IrzYy32ygmH52iDJmyl2DBn73LpIQ0S1mcZ28pRf2eCkN6nO2fls4s50Dw"
  }
}

```

This VC is failing verification
```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://credreg.net/ctdlasn/schema/context/json"
  ],
  "type": [
    "VerifiableCredential"
  ],
  "issuer": "did:key:z6Mkiy4qDuyvcVDHG7zcfEDjmmLchAuk8hy4uAJrQht3wio3",
  "issuanceDate": "2022-04-18T13:55:26Z",
  "credentialSubject": {
    "id": "did:key:z6MkfwmZep5ZvkHfeXszxhxEuvkmGFRc8H9Nv9ZaQG4vhFzZ",
    "schema:hasCredential": {
      "type": "ceterms:MicroCredential",
      "ceterms:name": "Ogi ogi",
      "ceterms:description": "This is a proof that things work!",
      "ceterms:relatedAction": {
        "type": "ceterms:CredentialingAction",
        "ceterms:startDate": "2022-04-18T11:55:10.968Z",
        "ceterms:endDate": "2022-04-20T11:55:10.968Z"
      },
      "ceterms:subject": [
        {
          "type": "ceterms:CredentialAlignmentObject",
          "ceterms:targetNodeName": {
            "en-US": "Making sure you know Javascript"
          }
        }
      ]
    }
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2022-04-27T18:44:51Z",
    "verificationMethod": "did:key:z6Mkiy4qDuyvcVDHG7zcfEDjmmLchAuk8hy4uAJrQht3wio3#z6Mkiy4qDuyvcVDHG7zcfEDjmmLchAuk8hy4uAJrQht3wio3",
    "proofPurpose": "assertionMethod",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..gC_aD029AQ8JSW8q0yLBjZ4_ZUja2eDuM37bapFUhhwUw4ndUBl7qFGID08FksBDZH8bBAOE8s3gAdC2-ZLXAg"
  }
}

```

The libraries and code for issuing and verifying the credentials is the same, which seems to imply there is something in the content that is causing the VC to not be verified.

**Comment by BenjaminMoe** [comment]
I'll have to go back and take a closer look at the errors being generated on the second verifiable credential, but my guess would be that the context being generated to sign isn't the same context being checked against verification.

There's also the use of [https://w3id.org/traceability/v1](https://w3c-ccg.github.io/traceability-vocab/#undefined-terms) in the first example. As this allows for JSON-LD errors while the vocabulary is still being defined to be able to sign ontop of JSON.

>This vocabulary uses '@vocab': 'https://w3id.org/traceability/#undefinedTerm' to disable JSON-LD related errors associated with Verifiable Credentials, issued about terms that have not yet been added here. 

It could be potentially possible there is a JSON-LD error with the first one which isn't getting reported because of this workaround. Right now I want to take the following steps.

1. Try to determine what context is being signed on in both cases
2. See if there is a slimmed down version of the second example that will work
3. Potentially create local versions of `https://w3id.org/traceability/v1` or `https://credreg.net/ctdlasn/schema/context/json` for debugging

**Comment by BenjaminMoe** [comment]
Log output of the error:

```
Hitting document request for this url: https://www.w3.org/2018/credentials/v1 { iri: 'https://www.w3.org/2018/credentials/v1' } WARNING
Hitting document request for this url: https://www.w3.org/2018/credentials/v1 { iri: 'https://www.w3.org/2018/credentials/v1' } WARNING
Hitting document request for this url: https://www.w3.org/2018/credentials/v1 { iri: 'https://www.w3.org/2018/credentials/v1' } WARNING
Hitting document request for this url: https://www.w3.org/2018/credentials/v1 { iri: 'https://www.w3.org/2018/credentials/v1' } WARNING
Hitting document request for this url: https://www.w3.org/2018/credentials/v1 { iri: 'https://www.w3.org/2018/credentials/v1' } WARNING
Hitting document request for this url: https://www.w3.org/2018/credentials/v1 { iri: 'https://www.w3.org/2018/credentials/v1' } WARNING
{
  verified: false,
  error: VerificationError: Verification error(s).
      at /home/benjamin/Github/verify-issues/verify/node_modules/@transmute/linked-data-proof/src/verify.ts:33:22
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    errors: [
      Error: Invalid signature.
          at Ed25519Signature2018._callee9$ (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/src/Ed25519Signature2018.ts:331:15)
          at tryCatch (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/node_modules/regenerator-runtime/runtime.js:63:40)
          at Generator.invoke [as _invoke] (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/node_modules/regenerator-runtime/runtime.js:294:22)
          at Generator.next (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/node_modules/regenerator-runtime/runtime.js:119:21)
          at asyncGeneratorStep (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/dist/ed25519-signature-2018.cjs.development.js:16:24)
          at _next (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/dist/ed25519-signature-2018.cjs.development.js:38:9)
          at processTicksAndRejections (internal/process/task_queues.js:95:5),
      Error: Invalid signature.
          at Ed25519Signature2018._callee9$ (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/src/Ed25519Signature2018.ts:331:15)
          at tryCatch (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/node_modules/regenerator-runtime/runtime.js:63:40)
          at Generator.invoke [as _invoke] (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/node_modules/regenerator-runtime/runtime.js:294:22)
          at Generator.next (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/node_modules/regenerator-runtime/runtime.js:119:21)
          at asyncGeneratorStep (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/dist/ed25519-signature-2018.cjs.development.js:16:24)
          at _next (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/dist/ed25519-signature-2018.cjs.development.js:38:9)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    ]
  }
}
```

I think this is similar to trace-vocab, where we need to regenerate the proof after changing a schema. Because the updated schema causes the context to change. Still a guess, need to find a way to output the exact context on sign to be able to verify that guess.

**Comment by vongohren** [comment]
Sounds interessting in terms of why the first one works. Dmitri from digitalbazaar made a successfuly signing with their world, but I did not when I reconstructed their world in this repo. But look forward to the continuance

**Comment by BenjaminMoe** [comment]
>Sounds interesting in terms of why the first one works.

It looks like I was wrong about that. I forked your repository and started playing around with it. And I managed to get your _complex_ example to verify by re-using the same document loader used to issue. Going to start to trace which url is specifically causing the issue, and if something needs to be done to patch or address it. 

https://github.com/BenjaminMoe/verify-issues/blob/main/verify/index.ts#L14
https://github.com/BenjaminMoe/verify-issues/blob/main/verify/transmute.ts#L15

```
========================
VERIFYING WITH COMPLEX
========================
Loading:  https://www.w3.org/2018/credentials/v1
Loading:  https://credreg.net/ctdlasn/schema/context/json
Loading:  https://www.w3.org/2018/credentials/v1
Loading:  https://credreg.net/ctdlasn/schema/context/json
Loading:  https://www.w3.org/2018/credentials/v1
Loading:  https://credreg.net/ctdlasn/schema/context/json
Loading:  https://www.w3.org/2018/credentials/v1
Loading:  https://credreg.net/ctdlasn/schema/context/json
Loading:  did:key:z6Mkiy4qDuyvcVDHG7zcfEDjmmLchAuk8hy4uAJrQht3wio3#z6Mkiy4qDuyvcVDHG7zcfEDjmmLchAuk8hy4uAJrQht3wio3
Loading:  did:key:z6Mkiy4qDuyvcVDHG7zcfEDjmmLchAuk8hy4uAJrQht3wio3#z6Mkiy4qDuyvcVDHG7zcfEDjmmLchAuk8hy4uAJrQht3wio3
{ verified: true }
Hitting document request for this url: https://www.w3.org/2018/credentials/v1 { iri: 'https://www.w3.org/2018/credentials/v1' } WARNING
Hitting document request for this url: https://www.w3.org/2018/credentials/v1 { iri: 'https://www.w3.org/2018/credentials/v1' } WARNING
Hitting document request for this url: https://www.w3.org/2018/credentials/v1 { iri: 'https://www.w3.org/2018/credentials/v1' } WARNING
Hitting document request for this url: https://www.w3.org/2018/credentials/v1 { iri: 'https://www.w3.org/2018/credentials/v1' } WARNING
{
  verified: false,
  error: VerificationError: Verification error(s).
      at /home/benjamin/Github/verify-issues/verify/node_modules/@transmute/linked-data-proof/src/verify.ts:33:22
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    errors: [
      Error: Invalid signature.
          at Ed25519Signature2018._callee9$ (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/src/Ed25519Signature2018.ts:331:15)
          at tryCatch (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/node_modules/regenerator-runtime/runtime.js:63:40)
          at Generator.invoke [as _invoke] (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/node_modules/regenerator-runtime/runtime.js:294:22)
          at Generator.next (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/node_modules/regenerator-runtime/runtime.js:119:21)
          at asyncGeneratorStep (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/dist/ed25519-signature-2018.cjs.development.js:16:24)
          at _next (/home/benjamin/Github/verify-issues/verify/node_modules/@transmute/ed25519-signature-2018/dist/ed25519-signature-2018.cjs.development.js:38:9)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    ]
  }
}
```

**Comment by BenjaminMoe** [comment]
Okay, I think i solved it. 

This context is being used to issue: https://github.com/vongohren/verify-issues/blob/main/issue/document/contexts/creg-context-v1.json

This context is being used to verify: https://github.com/vongohren/verify-issues/blob/main/verify/creg.json

These files are different, and that's what's causing the invalid signature issue. 

I think I solved it: 
https://github.com/vongohren/verify-issues/pull/2

**Comment by vongohren** [comment]
@BenjaminMoe that fixes everything yes, and I feel stupid now, but this does relate to a session at IIW recently https://docs.google.com/document/d/1ex_6aUqUOKEkOm2czOIlgSZZGwXKpdhy6G4_ARsHmrc/edit, that lead to this discussion and future work: https://github.com/decentralized-identity/interoperability/discussions/63
